Resources:
  GuardDutyDetector:
    Type: "AWS::GuardDuty::Detector"
    Properties:
      Enable: true

  {% set previousAccountId = 0 %}
  {% for Account in AWSAccounts %}
  {% if Account['Id'] != SecurityAccount %}
  GuardDutyMember{{Account['Id']}}:
    DependsOn:
      - GuardDutyDetector
      {% if previousAccountId > 0 %}
      - GuardDutyMember{{previousAccountId}}
      {% endif %}
    Type: "AWS::GuardDuty::Member"
    Properties:
      Status: "Invited"
      MemberId: "{{Account['Id']}}"
      Email: "{{Account['Email']}}"
      Message: "You are invited to enable Amazon Guardduty."
      DetectorId: !Ref GuardDutyDetector
      DisableEmailNotification: true
  {% set previousAccountId = Account['Id'] %}
  {% endif %}
  {% endfor %}