stack-set: guardduty-main
organization-variables: true
max-concurrent-percentage: 100
main-account: true
tags:
  ValidateMainAccount: true
  ValidateAllRegions: true
#  ValidateExcludedRegions: ap-northeast-3
