stack-set: guardduty-main
#all-regions: true
excluded-regions:
  - eu-north-1
organization-variables: true
max-concurrent-percentage: 100
tags:
#  ValidateAllRegions: true
  ValidateExcludedRegions: eu-north-1