{% set Roles = ['Admin', 'Developer', 'CloudFormationDeveloper', 'ReadOnly', 'SecurityAudit', 'Operations', 'TerraformPlan', 'TerraformApply'] %}

Resources:
  GroupManagement:
    Type: AWS::IAM::Group
    Properties:
      GroupName: GroupManagement
      Path: /admin/
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                - iam:AddUserToGroup
                Effect: Allow
                Resource:
                  - !GetAtt UserCredentialsManagement.Arn
              - Action:
                  - iam:AddUserToGroup
                  - iam:RemoveUserFromGroup
                Effect: Allow
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:group/admin/GroupManagement
                  - !GetAtt UserManagement.Arn
                  - !GetAtt AccountListing.Arn
                  - !GetAtt BillingReadAccess.Arn
                  - !GetAtt SecurityAudit.Arn
                  - !GetAtt LoggingReadAccess.Arn
                  {% for Role in Roles %}
                  - !Sub arn:aws:iam::${AWS::AccountId}:group/assume/Assume{{Role}}_*
                  {% endfor %}
                  - !Sub arn:aws:iam::${AWS::AccountId}:group/terraform/TerraformState_*
              - Action:
                  - iam:ListGroups
                  - iam:ListGroupsForUser
                  - iam:GetGroup
                  - iam:GetGroupPolicy
                  - iam:ListGroupPolicies
                  - iam:ListAttachedGroupPolicies
                  - iam:GetAccountAuthorizationDetails
                  - iam:GetAccountSummary
                  - iam:GetPolicy
                  - iam:GetPolicyVersion
                Effect: Allow
                Resource: '*'
          PolicyName: Policy

  {% for Account in AWSSubAccounts%}
  {% for Role in Roles %}
  {{Role}}Group{{Account['Id']}}:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Assume{{Role}}_{{Account['Name'] | resource}}_{{Account['Id']}}
      Path: /assume/
      Policies:
      - PolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Effect: Allow
              Resource:
                - arn:aws:iam::{{Account['Id']}}:role/Assumable{{Role}}Role
        PolicyName: {{Role}}Policy{{Account['Id']}}
  {% endfor %}
  {% endfor %}

{% if MainAccount != SecurityAccount %}
  BillingReadAccess:
    Type: AWS::IAM::Group
    Properties:
      GroupName: AssumeBillingView_Main_{{MainAccount}}
      Path: /assume/
      Policies:
      - PolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Effect: Allow
              Resource:
                - arn:aws:iam::{{MainAccount}}:role/AssumableBillingViewRole
        PolicyName: BillingViewPolicy{{MainAccount}}
{% endif %}

{% if LoggingAccount != SecurityAccount %}
  LoggingReadAccess:
    Type: AWS::IAM::Group
    Properties:
      GroupName: AssumeLoggingView_Logging_{{LoggingAccount}}
      Path: /assume/
      Policies:
      - PolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Effect: Allow
              Resource:
                - arn:aws:iam::{{LoggingAccount}}:role/AssumableLoggingViewRole
        PolicyName: LoggingViewPolicy{{LoggingAccount}}

  LoggingSecurityAudit:
    Type: AWS::IAM::Group
    Properties:
      GroupName: AssumeSecurityAudit_Logging_{{LoggingAccount}}
      Path: /assume/
      Policies:
      - PolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Effect: Allow
              Resource:
                - arn:aws:iam::{{LoggingAccount}}:role/AssumableSecurityAuditRole
        PolicyName: SecurityAuditPolicy{{LoggingAccount}}

{% endif %}