Resources:
  GuardDutyDetector:
    Type: "AWS::GuardDuty::Detector"
    Properties:
      Enable: true

  GuardDutyMaster:
    DependsOn: GuardDutyDetector
    Type: "AWS::GuardDuty::Master"
    Properties:
      DetectorId: !Ref GuardDutyDetector
      MasterId: "{{MainAccount}}"
