Parameters:
  AuditingGlueDatabaseName:
    Type: String
    Default: auditing


Resources:
  AthenaQueryResults:
    Type: 'AWS::S3::Bucket'

  AuditingGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Ref AuditingGlueDatabaseName
      CatalogId: !Ref AWS::AccountId

Outputs:
  AthenaQueryResultsBucketName:
    Value: !Ref AthenaQueryResults
    Export:
      Name: !Sub ${ExportPrefix}:AthenaQueryResultsBucketName
  AuditingGlueDatabaseName:
    Value: !Ref AuditingGlueDatabase
    Export:
      Name: !Sub ${ExportPrefix}:AuditingGlueDatabaseName
