stack-set: auditing-configuration
capabilities:
  - CAPABILITY_IAM
all-accounts: true
main-account-parameter: true
max-concurrent-percentage: 100
#parameters:
#  DeliveryFrequency: Six_Hours
#  CloudTrailLogsRetentionInDays: 90
tags:
  ValidateAllAccounts: true
  ValidateAllRegions: true
#  ValidateExcludedRegions: ap-northeast-3
