stack-set: auditing-configuration
capabilities:
  - CAPABILITY_IAM
all-accounts: true
main-account-parameter: true
max-concurrent-percentage: 100
parameters:
  DeliveryFrequency: TwentyFour_Hours
  CloudTrailLogsRetentionInDays: 7
tags:
  ValidateAllAccounts: true
#  ValidateAllRegions: true
  ValidateExcludedRegions: eu-north-1
