stack: sso-permissions
#vars:
#  AllowedRegions: us-east-1
#  TerraformPermissionSets: true
#  TerraformRemoteStateBucketPrefix: terraform-state
#  TerraformLockingTableName: terraform-locks
#  TerraformLockingTableRegion: us-east-1
#  TerraformEncryptionAliasName: terraform
#  AllowDevsIAMViews: true
#  AllowDevsIAMLimitedAdmin: true
parameters:
  SSOInstanceArn: arn:aws:sso:::instance/ssoins-XXXXXXXXXXXXXXXX
create-missing: true
