stack-set: stack-set-execution-role
execution-role-name: OrganizationAccountAccessRole
capabilities:
  - CAPABILITY_NAMED_IAM
main-account-parameter: true
max-concurrent-percentage: 100
all-subaccounts: true
tags:
  ValidateAllSubAccounts: true
